using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ACS.SPiiPlusNET;

namespace IO
{
    public class EthercatIO : IInputOutput
    {
        private Api Ch;
        private int BaseAddressOffset;
        private int InputModuleNum;
        private int OutputModuleNum;
        private int InputModuleAddrInc;
        private int OutputModuleAddrInc;
        private const string InputVariableName = "InputModule";
        private const string OutputVariableName = "OnputModule";
        private const string GlobalDefine = "GLOBAL INT ";
        private string NewLine = Environment.NewLine;

        public EthercatIO(Api acsController, int baseAddressOffset, 
            int inputModuleNum, int outputModuleNum, int inputModuleAddrInc = 4, int outputModuleAddrInc = 2)
        {
            Ch = acsController;
            BaseAddressOffset = baseAddressOffset;
            InputModuleNum = inputModuleNum;
            OutputModuleNum = outputModuleNum;
            InputModuleAddrInc = inputModuleAddrInc;
            OutputModuleAddrInc = outputModuleAddrInc;
        }

        public void Setup()
        {
            //DeclareVariable();
            DeclareVariableInDBuffer();
        }

        /// <summary>
        /// Global variable should be define in D buffer.
        /// </summary>
        private void DeclareVariable()
        {
            //Warning : Deletes all persistent global variables.
            //Todo: comment out
            Ch.ClearVariables();

            for (int i = 0; i < InputModuleNum; i++)
            {
                Ch.DeclareVariable(AcsplVariableType.ACSC_INT_TYPE, GetInputName(i));
            }

            for (int i = 0; i < OutputModuleNum; i++)
            {
                Ch.DeclareVariable(AcsplVariableType.ACSC_INT_TYPE, GetOutputName(i));
            }
        }

        private void DeclareVariableInDBuffer()
        {            
            string Warning = "! Warning, generated by Host for digital input and output, do NOT change." + NewLine;

            string inputDefine = string.Empty;
            for (int i = 0; i < InputModuleNum; i++)
            {
                inputDefine += GlobalDefine + GetInputName(i) + NewLine;
            }

            string outputDefine = string.Empty;
            for (int i = 0; i < OutputModuleNum; i++)
            {
                outputDefine += GlobalDefine + GetOutputName(i) + NewLine;
            }

            string program = Warning + inputDefine + outputDefine;
            ProgramBuffer DBuffer = (ProgramBuffer)(Convert.ToInt16(Ch.GetDBufferIndex()));

            string originProgram = Ch.UploadBuffer(DBuffer);
            if (originProgram != null)
            {
                if (originProgram.Contains(InputVariableName + BaseAddressOffset) == false)
                {
                    Ch.AppendBuffer(DBuffer, program);

                    for (int i = 0; i < 9; i++)
                    {
                        Ch.ClearBuffer((ProgramBuffer)i, 1, 2000);
                    }
                    Ch.CompileBuffer(DBuffer);
                }
            }

            MapEtherCAT();
        }

        private void MapEtherCAT()
        {
            for (int i = 0; i < InputModuleNum; i++)
            {
                Ch.MapEtherCATInput(MotionFlags.ACSC_NONE, GetInputModuleAddress(i), GetInputName(i));
            }

            for (int i = 0; i < OutputModuleNum; i++)
            {
                Ch.MapEtherCATOutput(MotionFlags.ACSC_NONE, GetOutputModuleAddress(i), GetOutputName(i));
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="moduleId">Zero based</param>
        /// <returns></returns>
        private string GetInputName(int moduleId)
        {
            return InputVariableName + (BaseAddressOffset + moduleId * InputModuleAddrInc);
        }

        private string GetOutputName(int moduleId)
        {
            return OutputVariableName + (BaseAddressOffset + moduleId * OutputModuleAddrInc);
        }

        private int GetInputModuleAddress(int moduleId)
        {
            return BaseAddressOffset + moduleId * InputModuleAddrInc;
        }

        private int GetOutputModuleAddress(int moduleId)
        {
            return BaseAddressOffset + moduleId * OutputModuleAddrInc;
        }

        public bool GetInput(int moduleId, int inputPinNum)
        {
            string variableName = GetInputName(moduleId);
            // ? negative number?
            int inputValue = Convert.ToInt32(Ch.ReadVariable(variableName));

            //Get a signed byte back, convert to a unsigned byte.
            inputValue = inputValue > 0 ? inputValue : inputValue + 256;

            return GetBit(inputValue, inputPinNum);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="value"></param>
        /// <param name="bitPosition">0 based index</param>
        private bool GetBit(int value, int bitPosition)
        {
            return (value & (1 << bitPosition)) != 0;
        }

        private void SetBit(ref int value, int bitPosition)
        {
            value |= 1 << bitPosition;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="value"></param>
        /// <param name="bitPosition">0 based index</param>
        public static void ResetBit(ref int value, int bitPosition)
        {
            value &= ~(1 << bitPosition);
        }

        public bool GetOutput(int moduleId, int outputPinNum)
        {
            string variableName = GetOutputName(moduleId);
            // ? negative number?
            int OutputValue = Convert.ToInt32(Ch.ReadVariable(variableName));

            return GetBit(OutputValue, outputPinNum);
        }

        public void SetOutput(int moduleId, int outputPinNum, bool value)
        {
            string variableName = GetOutputName(moduleId);
            int OutputValue = Convert.ToInt32(Ch.ReadVariable(variableName));

            if (value == true)
            {
                SetBit(ref OutputValue, outputPinNum);
            }
            else
            {
                ResetBit(ref OutputValue, outputPinNum);
            }

            Ch.WriteVariable(OutputValue, variableName, ProgramBuffer.ACSC_NONE);
        }

        public void SetOutput(Output output, bool value)
        {
            int outputValue = (int)output;
            int moduleId = outputValue / 10;
            int outputPinNum = outputValue % 10;

        }

        public bool Getinput(Input input)
        {
            int inputValue = (int)input;
            int moduleId = inputValue / 10;
            int inputPinNum = inputValue % 10;

            return false;
        }

        public void SetOutput(int output, bool value)
        {
            int moduleId = output / 10;
            int outputPinNum = output % 10;

        }

        public bool Getinput(int input)
        {
            int moduleId = input / 10;
            int inputPinNum = input % 10;

            return false;
        }
    }
}
